name: Build and Deploy Application
on:
  push:
    branches:
      - 'master'
      - 'releases/**'
      - 'release/**'
      - 'develop'
      - 'feature/**'
      - 'feat/**'
      - 'hotfix/**'
    paths-ignore:
      - 'docs/**'
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Create docker image name
        id: docker-image
        run: |
            BRANCH_NAME=${{ github.ref_name }}
            IMAGE_NAME=${BRANCH_NAME}_${{ github.sha }}
            echo "IMAGE_NAME=${IMAGE_NAME}" >> $GITHUB_OUTPUT
      - name: Extract repository name
        id: extract-repository-name
        run: |
            REPO_NAME=$(echo "${{ github.repository }}" | cut -d '/' -f 2)
            echo "REPO_NAME=${REPO_NAME}" >> $GITHUB_OUTPUT
      - name: Login to Docker registry
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: '${{ secrets.DOCKER_USERNAME }}'
          password: '${{ secrets.DOCKER_PASSWORD }}'
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: >
            docker.io/${{ secrets.DOCKER_USERNAME }}/${{ steps.extract-repository-name.outputs.REPO_NAME }}:${{ steps.docker-image.outputs.IMAGE_NAME }}
