name: Build and Deploy Application
on:
  push:
    branches:
      - 'master'
      - 'releases/**'
      - 'release/**'
      - 'develop'
      - 'feature/**'
      - 'feat/**'
      - 'hotfix/**'
    paths-ignore:
      - 'docs/**'
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Get Branch Name
        id: image-name
        run: |
          BRANCH_NAME=${{ github.ref }}
          BRANCH_NAME=${BRANCH_NAME#refs/heads/}  # Remove "refs/heads/" prefix
          BRANCH_NAME=${BRANCH_NAME//\//}         # Remove any backslashes
          IMAGE_NAME=${BRANCH_NAME}_${{ github.sha }}
          echo "::set-output name=IMAGE_NAME::$IMAGE_NAME"
      - name: Login to Docker registry
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: '${{ secrets.DOCKER_USERNAME }}'
          password: '${{ secrets.DOCKER_PASSWORD }}'
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/actions/Dockerfile
          push: true
          tags: >
            docker.io/${{ secrets.DOCKER_USERNAME }}/${{ env.GITHUB_REPOSITORY#*/ }}:${{
            steps.image-name.outputs.IMAGE_NAME }}